name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # GitHub의 Actions 탭에서 이 워크플로를 수동으로 실행할 수 있습니다.
  workflow_dispatch:

# 이 작업이 리포지토리를 복제하고 페이지 배포를 생성하도록 허용합니다.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload your site
        uses: withastro/action@v6
        with:
          node-version: 22 # 사이트를 빌드하는 데 사용해야 하는 특정 버전의 Node입니다. 기본값은 22입니다. (선택 사항)
        #   path: . # 저장소 내 Astro 프로젝트의 루트 위치입니다. (선택 사항)
        #   package-manager: pnpm@latest # 종속성을 설치하고 사이트를 빌드하는 데 사용해야 하는 노드 패키지 관리자입니다. lockfile을 기반으로 자동으로 감지됩니다. (선택 사항)
        #   build-cmd: pnpm run build # 사이트를 빌드하는 데 실행할 명령입니다. 기본적으로 패키지 빌드 스크립트/작업을 실행합니다. (선택 사항)
        # env:
        #   PUBLIC_POKEAPI: 'https://pokeapi.co/api/v2' # 변수 값에는 작은따옴표를 사용합니다. (선택 사항)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
